### ISSUE TITLE
Found issue with website

### ISSUE THREAD

**Issue by vbchurchill** [libscie/libscie.org#64]
While browsing your website, I found the following issue:

Hi! I clicked the link to sign-up for your newsletter, but it's requiring a Google account log-in. My work email is not a Google one and so I cannot log in to sign-up. May I sign-up through here? My work email is: churchill@hnu.edu. 

Thank you!

**Comment by chartgerink** [comment]
My apologies @vbchurchill 😅 I updated the settings and the link should now work for you 😊 

https://forms.gle/ebzsSRN8erubCTW5A

**Comment by vbchurchill** [comment]
Awesome! I've signed up. I enjoyed your presentation at the USETDA conference yesterday. I'm looking forward reading your updates.
