### ISSUE TITLE
Project SVGs causing some issues

### ISSUE THREAD

**Issue by chartgerink** [libscie/libscie.org#9]
The project Hex SVGs added at the last minute are causing some issues. Most notably:

- [ ] The wave behind the hero no longer appears
- [ ] The Hexes themselves don't appear in Safari

This issue was triangulated by removing the SVGs only, after which the page worked again.

@psobrakseaton any idea what is up with the SVG assets that may cause this? Did they adhere to the SVG asset production guideline you set up before? Guess we should've inspected before merging 😅

**Comment by psobrakseaton** [comment]
Yeah, I think the issue stems from how the old SVGs are built compared to the new ones. I did my best in the rush to try to make all the settings the same, but to no avail.

**Comment by chartgerink** [comment]
No worries - do you have any suggestions how to move forward? I am also happy to put in PNGs for now.

**Comment by psobrakseaton** [comment]
I think I would rather they be SVGs. Give me some time to work through some of the issues. I'll send you more assets in a few.
